### ISSUE TITLE
Error with share facebook

### ISSUE THREAD

**Issue by namthang** [tykarol/redux-isomorphic-starter-kit#1]
Hi. 
I used your code for my project, but when share facebook with link http://domain/test/a . Facebook only get tit App - Demo (Can not get title Test-1 with TestPage). 
Can you help me.
Thanks so much.

**Comment by tykarol** [comment]
This heppens because data on server side is not fetched (it is first on todo list). When you check /test/a page source code you saw default title "App - Demo".

**Comment by namthang** [comment]
Thanks for your answer. 
how to rewrite that code?

**Comment by tykarol** [comment]
Check new version, I add simple implementation for prefeching data on SSR

**Comment by namthang** [comment]
Wow, thanks you so much. Have a good day. :)
