### ISSUE TITLE
Auth middleware in route

### ISSUE THREAD

**Issue by namthang** [tykarol/redux-isomorphic-starter-kit#2]
Hi Author. 
Thanks for your code, very clear and easy for starter, i have a problem with auth, in routes.js, how i can add auth middleware. 
Thanks so much.

**Comment by tykarol** [comment]
Currently this is not available, but you can write it ;) In Google you can find many examples how do this eg. https://gist.github.com/iNikNik/1eabfc6bcc132384368c

**Comment by namthang** [comment]
Thanks so much
